CREATE TABLE IF NOT EXISTS books (
  id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  year INTEGER NOT NULL,
  clicks INTEGER NOT NULL DEFAULT 0,
  image_url VARCHAR(255)
);